import Head from "next/head";
import { Inter } from "next/font/google";

import Header from "@/components/Header";

import Content from "@/components/container/Content";
import MainImage from "@/components/MainImageMovies";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie Web site(仮)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <MainImage />
      <Content />

     <Footer />

    </>
  );
}
