import LeftSidePicMain from "./LeftSidePicMain";
import RightSideDetailMain from "./RightSideDetailMain";
import FavoriteWatch from "./FavoriteWatch";
import CastList from "./CastList";
import { Box } from "@mui/material";
import { useEffect, useState } from "react";
import axios from "axios";
import Head from "next/head";

import { Drama } from "@/src/state/category";

const SinglePageInfo = ({ id }: { id: string }) => {
  const apikey = process.env.NEXT_PUBLIC_API_KEY;

  const [leftPic, setLeftPic] = useState<Drama | null>(null);
  const [rightSideDetail, setRightSideDetail] = useState<Drama | null>(null);
  const [casts, setCasts] = useState([]);

  const fetchMovieInfo = async () => {
    try {
      const response = await axios.get(
        `https://api.themoviedb.org/3/tv/${id}?api_key=${apikey}`
      );
      setLeftPic(response.data);
      setRightSideDetail(response.data);
    } catch (error) {
      console.log(error);
    }
  };

  const fetchCasts = async () => {
    try {
      const response = await axios.get(
        `https://api.themoviedb.org/3/tv/${id}/credits?api_key=${apikey}`
      );
      setCasts(response.data.cast);
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    fetchMovieInfo();
    fetchCasts();
  }, [id]);

  const extractYearFromDate = (dateString: string): string => {
    return dateString.substring(0, 4);
  };
  return (
    <>
      <Head>
        <title>{leftPic?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{ display: "flex", justifyContent: "center", marginTop: "50px" }}
      >
        {/* このページでidを取得しているからidを下の階層に渡さなくても良い？ */}
        <LeftSidePicMain leftPic={leftPic} />
        <Box sx={{ flexDirection: "column", width: "60%" }}>
          <RightSideDetailMain
            rightSideDetail={rightSideDetail}
            extractYearFromDate={extractYearFromDate}
          />
          <FavoriteWatch />
          <CastList casts={casts} />
        </Box>
      </div>
    </>
  );
};

export default SinglePageInfo;
